### ISSUE TITLE
No logs on most error cases

### ISSUE THREAD

**Issue by t1agob** [music-tribe/azadjwtvalidation#6]
**Problem statement**
There are multiple cases where errors are not being logged. Also, despite the fact the log messages are descriptive they don't provide enough context to help identify the root cause.

**Proposed solution**
1. Detailed error messages should be logged every time a HTTP error is returned. 
2. Allow optional injection of http request headers

_Plugin configuration suggestion_
```yaml
keysurl: "https://jwks.keys"
issuer: "https://issuer.test"
audience: "audience1,audience2"
roles:
  - Test.Role.1
  - Test.Role.2
matchallroles: true
loglevel: "DEBUG"
logheaders: 
  - X-Request-Id
  - Host
```
Having this would allow easier troubleshooting in error scenarios.
